(function() {
    window.addEventListener('load', function() {
      if (window.location.pathname.indexOf('/forms/d') === 0) { // If we're on the form page
        submitRandomForm();
      } else if (window.location.pathname.indexOf('/forms/u') === 0) { // If we're on the "submitted" page
        goBackToForm();
      }
  
      function submitRandomForm() {
        // Size
        var radios     = document.querySelectorAll(".appsMaterialWizToggleRadiogroupRadioButtonContainer"),
            radioIndex = Math.floor(Math.random() * radios.length);
        radios[radioIndex].click();
  
        // Print
        var checkboxes    = document.querySelectorAll(".appsMaterialWizTogglePapercheckboxCheckbox"),
            checkboxIndex = Math.floor(Math.random() * checkboxes.length);
        checkboxes[checkboxIndex].click();
  
        // Age (between 16 and 45)
        var age = Math.floor(Math.random() * 30) + 16;
        document.querySelector(".quantumWizTextinputPaperinputInput").value = age;
  
        // Submit
        document.querySelector(".freebirdFormviewerViewCenteredContent .appsMaterialWizButtonPaperbuttonLabel").click();
      }
  
      function goBackToForm() {
        window.location.href = 'https://docs.google.com/forms/d/e/1FAIpQLSd7GueJGytOiQpkhQzo_dCU0oWwbk3L1htKblBO1m14VHSpHw/viewform';
      }
    });
  })();


  //https://docs.google.com/forms/d/e/1FAIpQLSfP2iAdHD552Drk696r6VOEwCJSewns9fNaY1w5CRVuN_3t3g/viewform?usp=pp_url&entry.1208713669=100L&entry.2131434838=How+can+I+know+which+building+is+the+right+venue?&entry.1723334282=You+can+ask+any+nearby+student+for+confirmation&entry.1826106239=How+did+I+end+up+in+this+University&entry.1417530113=You+most+likely+entered+because+you+were+successful+in+the+entrance+examinations.+If+the+answer+is+not+what+you+want,+then+look+deep+inside+yourself+to+find+the+answer&entry.1692459364=One+particular+problem+was+getting+access+to+the+correct+timetable&entry.661419317=You+can+get+the+correct+timetable+from+your+class+representative+or+your+departmental+exam+officer&entry.719806540=How+should+DE+students+deal+with+clashing+time+table&entry.174409468=You+can+request+for+a+change+of+lecture+time+for+one+of+the+courses.+Meet+up+with+your+departmental+officer+to+further+sort+out+the+issue&entry.581328273=Can+I+use+wifi+for+free&entry.118299674=No.+You+have+to+purchase+it+from+crc&entry.767814484=shuttle,+keke-napep+and+taxi-drops&entry.422470210=join+whatsapp+groups+and+frequently+check+your+departmental+notice+board&entry.1967271397=You+can+buy+login+details+from+the+crc+or+their+branch+closest+to+you&entry.1148354280=You+can+visit+the+student+affairs+building+to+get+information+regarding+student+housing.+You+can+also+ask+around+for+housing+agents+to+attend+to+you&entry.1055762946=You+can+get+such+information+from+the+student+affairs+building.+You+can+also+ask+your+peers+and+your+departmental+officers.&entry.1778061262=You+can+visit+the+student+union+building+to+ask+for+tutorial+dates.+You+can+also+ask+nearby+religious+centers+if+they+are+hosting+tutorial+sessions&entry.1351850105=There+are+indoor+recreational+facilities+in+the+building+beside+the+student+union+building.+There+are+also+outdoor+recreational+facilities+in+the+sports+complex&entry.1219229766=The+annual+freshers+party+is+one+to+look+forward+to.+It+holds+every+academic+year+and+is+organized+by+the+student+union+government&entry.30550000=The+school+uses+a+5.0+grading+system.+An+A+ranges+from+70-100+and+weighs+5+points,+a+B+from+60-70+and+weighs+4+points,+a+C+from+50-60+and+weighs+3+points,+a+D+from+45-50+and+weighs+2+points+and+an+F+from+0-44.+Each+courses+has+a+number+of+units+assigned+to+it.+the+sum+of+the+multiplication+of+each+courses+unit+with+their+weigh+gives+your+score+which+will+be+compared+to+the+maximum+score+possible+and+then+your+corresponding+GPA+will+be+calculated.+You+can+get+more+information+from+the+student+union+building&entry.1875711917=The+health+center+is+free+for+students,+you+only+need+to+bring+along+your+ID+card.+The+sports+complex+has+fitness+facilities+that+can+be+used+by+all+students
  //https://docs.google.com/forms/d/e/1FAIpQLSfP2iAdHD552Drk696r6VOEwCJSewns9fNaY1w5CRVuN_3t3g/viewform?usp=pp_url&entry.1208713669=200L&entry.2131434838=How+many+hours+are+for+classes&entry.1723334282=2+hours+for+classes+and+1+hour+for+lab+practicals&entry.1826106239=Where+is+the+chemistry+lab&entry.1417530113=It+is+in+the+School+of+science+building&entry.1692459364=How+many+weeks+is+for+exam&entry.661419317=It+varies+but+usually+three+weeks&entry.719806540=Where+can+I+complain+about+a+staff&entry.174409468=You+can+make+your+complaints+at+the+student+affairs+building&entry.581328273=When+is+mid+semester+break&entry.118299674=It+is+not+static.+Check+the+school+calendar&entry.767814484=Shuttle,+cab+and+Tricycles&entry.422470210=Through+circulars,+WhatsApp+groups,+the+school+website,+the+school+Facebook+page&entry.1967271397=Procurement+of+Wi-Fi+pass+from+CRC+or+faculty+libraries.&entry.1148354280=On+the+school+portal+and+through+housing+agents&entry.1055762946=Through+your+department+staff+and+the+student+affairs&entry.1778061262=You+can+visit+any+nearby+mosque+or+church+to+ask+them+about+their+tutorial+schedule&entry.1351850105=There+are+two+pitches+for+football,+and+courts+for+basketball,+tennis+and+there+is+also+a+gym&entry.1219229766=Faculty+week+and+Voting+(SUG+and+Faculty)&entry.30550000=By+Grading%0AA+%3D+70-100%0AB+%3D+60-69%0AC+%3D+50-59%0AD+%3D+45-49%0AF+%3D+44%0A&entry.1875711917=For+the+fitness,+one+would+need+to+obtain+a+gym+subscription+there+at+the+gym+by+paying+a+token+for+registration.
  //https://docs.google.com/forms/d/e/1FAIpQLSfP2iAdHD552Drk696r6VOEwCJSewns9fNaY1w5CRVuN_3t3g/viewform?usp=pp_url&entry.1208713669=300L&entry.2131434838=Where+can+I+find+the+best+places+to+eat+on+campus?&entry.1723334282=Savour+is+arguably+the+best+eatery+on+the+campus.+It+is+located+in+the+student+union+building&entry.1826106239=How+can+I+make+friends+and+build+a+social+circle?&entry.1417530113=Be+more+proactive.+Talk+to+people+and+don't+shy+away+from+conversations.&entry.1692459364=How+do+I+deal+with+homesickness+or+feeling+overwhelmed?&entry.661419317=You+can+talk+to+your+friends+for+emotional+support.+You+can+also+visit+the+student+affairs+building+for+moral+and+emotional+support.&entry.719806540=How+can+I+build+a+professional+network+while+in+university?&entry.174409468=Engage+with+your+peers+and+attend+conferences+and+seminars.+The+more+you+expose+yourself+to+people,+the+more+you+build+connections&entry.581328273=What+are+the+important+deadlines+for+tuition+payments?&entry.118299674=The+deadline+for+tution+payment+depends+on+the+semester+and+it+varies.+But+there+is+usually+a+grace+of+about+2+months&entry.767814484=There+are+3+major+transportation+options:+shuttle+buses,+tricycle,+and+taxi-drops&entry.422470210=Join+communities+and+whatsapp+groups&entry.1967271397=Go+to+the+CRC+or+to+their+representative+in+your+school&entry.1148354280=Majorly+WhatsApp+groups+or+personal+house+hunting&entry.1055762946=Through+your+department+staff+and+the+student+affairs&entry.1778061262=If+any+is+announced+in+class+or+WhatsApp+groups&entry.1351850105=There+are+indoor+recreational+facilities+in+the+building+beside+the+student+union+building.+There+are+also+outdoor+recreational+facilities+in+the+sports+complex&entry.1219229766=The+annual+freshers+party+is+one+to+look+forward+to.+It+holds+every+academic+year+and+is+organized+by+the+student+union+government&entry.30550000=Proper+details+about+this+is+provided+in+your+departmental+hand+book&entry.1875711917=A+visit+to+the+health+center+reception+and+speaking+to+the+nurses+there+would+help.
  //https://docs.google.com/forms/d/e/1FAIpQLSfP2iAdHD552Drk696r6VOEwCJSewns9fNaY1w5CRVuN_3t3g/viewform?usp=pp_url&entry.1208713669=100L&entry.2131434838=What's+the+best+way+to+approach+professors+for+help+or+guidance?&entry.1723334282=Just+meet+up+with+them+and+politely+ask+them+if+they+can+assist+you.+If+they+are+unable+to+assist,+they+will+refer+you+to+someone+who+can.&entry.1826106239=How+do+I+create+an+effective+study+schedule?&entry.1417530113=Using+your+timetable,+can+create+a+study+schedule+that+properly+balances+study+and+rest+times&entry.1692459364=What+resources+are+available+for+academic+support?&entry.661419317=The+school+library+is+your+greatest+resouce,+your+departmental+library+is+also+a+great+source.&entry.719806540=How+do+I+join+clubs+or+student+organizations?&entry.174409468=You+can+inquire+from+your+peers+and+seniors+about+which+clubs+are+recruiting+and+apply.&entry.581328273=What+are+the+available+housing+options+for+subsequent+years?&entry.118299674=You+can+apply+for+on-campus+hostels+or+off-campus+lodges+and+subsequently+stay+there&entry.767814484=Shuttles(buses)+and+tricycles&entry.422470210=You+can+check+your+departments+notice+board+or+your+WhatsApp+group&entry.1967271397=Through+the+Computer+resource+Center&entry.1148354280=Mostly+through+WhatsApp+groups+or+personal+house+hunting&entry.1055762946=The+students+affairs+building+and+your+department+staff&entry.1778061262=You+can+visit+any+nearby+mosque+or+church+or+SUB+building&entry.1351850105=There+is+a+gym+near+SUB&entry.1219229766=Awopegba+football+competition&entry.30550000=Proper+details+about+this+is+provided+in+your+departmental+hand+book&entry.1875711917=To+access+the+university%E2%80%99s+health+facilities,+you+visit+the+University+health+center+with+your+school+ID+card+to+access+the+fitness+facilities+you+visit+the+centers+and+ask+for+guidance+on+how+to+proceed
  //https://docs.google.com/forms/d/e/1FAIpQLSfP2iAdHD552Drk696r6VOEwCJSewns9fNaY1w5CRVuN_3t3g/viewform?usp=pp_url&entry.1208713669=100L&entry.2131434838=How+can+I+find+internships+or+part-time+jobs+related+to+my+field?&entry.1723334282=You+can+inquire+from+your+departmental+officers+if+they+are+knowledgeable+about+any+open+positions+related+your+field.&entry.1826106239=When+should+I+start+thinking+about+post-graduation+plans?&entry.1417530113=As+soon+as+you+start+school,+you+should+start+envisioning+what+you+want+to+do+with+your+life+post-graduation&entry.1692459364=How+do+I+effectively+manage+a+heavy+workload+and+multiple+assignments?&entry.661419317=start+doing+the+work+little+by+little+and+steadily.+You+can+also+ask+for+help+from+friends.+Also+ensure+that+you+don't+develop+such+backlog+of+works&entry.719806540=What+are+some+recommended+study+strategies+for+different+subjects?&entry.174409468=For+MTS+101,+study+the+practical+manuals+very+well+and+for+MEE+101,+practice+a+lot&entry.581328273=How+do+I+prepare+for+exams+and+manage+test+anxiety?&entry.118299674=start+preparing+for+exams+as+early+as+the+beginning+of+the+semester.+This+makes+exam+and+test+reading+much+smoother+and+reduces+anxiety&entry.767814484=Shuttle,+cab+and+Tricycles&entry.422470210=Through+circulars,+WhatsApp+groups,+the+school+website,+the+school+Facebook+page&entry.1967271397=Procurement+of+Wi-Fi+pass+from+CRC+or+faculty+libraries.&entry.1148354280=On+the+school+portal+and+through+housing+agents&entry.1055762946=The+students+affairs+building+and+your+department+staff&entry.1778061262=You+can+visit+the+student+union+building+to+ask+for+tutorial+dates.+You+can+also+ask+nearby+religious+centers+if+they+are+hosting+tutorial+sessions&entry.1351850105=There+are+two+pitches+for+football,+and+courts+for+basketball,+tennis+and+there+is+also+a+gym&entry.1219229766=Freshers+night&entry.30550000=The+school+uses+a+5.0+grading+system.+An+A+ranges+from+70-100+and+weighs+5+points,+a+B+from+60-70+and+weighs+4+points,+a+C+from+50-60+and+weighs+3+points,+a+D+from+45-50+and+weighs+2+points+and+an+F+from+0-44.+Each+courses+has+a+number+of+units+assigned+to+it.+the+sum+of+the+multiplication+of+each+courses+unit+with+their+weigh+gives+your+score+which+will+be+compared+to+the+maximum+score+possible+and+then+your+corresponding+GPA+will+be+calculated.+You+can+get+more+information+from+the+student+union+building&entry.1875711917=To+access+the+university%E2%80%99s+health+facilities,+you+visit+the+University+health+center+with+your+school+ID+card+to+access+the+fitness+facilities+you+visit+the+centers+and+ask+for+guidance+on+how+to+proceed
  //https://docs.google.com/forms/d/e/1FAIpQLSfP2iAdHD552Drk696r6VOEwCJSewns9fNaY1w5CRVuN_3t3g/viewform?usp=pp_url&entry.1208713669=100L&entry.2131434838=What+are+the+best+ways+to+budget+my+expenses+as+a+student?&entry.1723334282=Try+to+spend+as+little+as+possible+on+frivolities.+Also+prioritize+cooking+over+eating+out+as+it+is+cheaper&entry.1826106239=Are+there+job+opportunities+on+or+off-campus+that+cater+to+student+schedules?&entry.1417530113=Yes+there+are.+Go+and+inquire+at+the+student+affairs+building+or+ask+your+departmental+officers+and+mates&entry.1692459364=How+can+I+minimize+student+loan+debt?&entry.661419317=Nigeria+does+not+currently+use+the+student+loan+dept.+The+Tinubu+regime+is+planning+to+introduce+it+though.&entry.719806540=Where+can+I+find+information+about+grants+or+financial+aid+specific+to+my+situation?&entry.174409468=You+can+inquire+at+the+student+affairs+building&entry.581328273=Where+is+the+student+affairs+building&entry.118299674=It+is+opposite+the+Senate+building.+It+is+beside+T.I+Francis+auditorium.&entry.767814484=There+are+3+major+transportation+options:+shuttle+buses,+tricycle,+and+taxi-drops&entry.422470210=Through+circulars,+WhatsApp+groups,+the+school+website,+the+school+Facebook+page&entry.1967271397=You+can+buy+login+details+from+the+crc+or+their+branch+closest+to+you&entry.1148354280=You+can+visit+the+student+affairs+building+to+get+information+regarding+student+housing.+You+can+also+ask+around+for+housing+agents+to+attend+to+you&entry.1055762946=You+can+get+such+information+from+the+student+affairs+building.+You+can+also+ask+your+peers+and+your+departmental+officers.&entry.1778061262=You+can+visit+the+student+union+building+to+ask+for+tutorial+dates.+You+can+also+ask+nearby+religious+centers+if+they+are+hosting+tutorial+sessions&entry.1351850105=There+are+indoor+recreational+facilities+in+the+building+beside+the+student+union+building.+There+are+also+outdoor+recreational+facilities+in+the+sports+complex&entry.1219229766=The+annual+freshers+party+is+one+to+look+forward+to.+It+holds+every+academic+year+and+is+organized+by+the+student+union+government&entry.30550000=Proper+details+about+this+is+provided+in+your+departmental+hand+book&entry.1875711917=To+access+the+university%E2%80%99s+health+facilities,+you+visit+the+University+health+center+with+your+school+ID+card+to+access+the+fitness+facilities+you+visit+the+centers+and+ask+for+guidance+on+how+to+proceed
  //